models.py
from __future__ import division

import numpy as np
import string

import otree.models
from otree.db import models
from otree import widgets
from otree.common import Currency as c, currency_range, safe_json
from otree.constants import BaseConstants
from otree.models import BaseSubsession, BaseGroup, BasePlayer

author = 'Hernán Villamizar'

doc = """
Real Effort Task - Letter Count
This is the competition part to a Tullock Contest in form of a Real Effort Task and an Investment Decision
"""


class Constants(BaseConstants):
    name_in_url = 'tullock_Income_RET'
    players_per_group = 3
    num_rounds = 8

    t = 180  # Total Time in seconds available for both solving and staying in switch
    time_in_minutes = t / 60

    tokensper_string = 1
    tokensper_string_high = 2
    eurosper_token = c(0.1)  # make sure to change it in both models.py
    secondsper_token = 10

    increase_per_string = 4

    # this is a summarized instruction to be shown under each sequence as a reminder:
    instructions_summarized = 'Tullock_Income_RET/InstructionsSum.html'

    # Taxation Treatment
    # The following variables allow to introduce a treatment of taxation and redistribution

    treatment = True
    tax_rate = 0.3
    tax_rate_percent = tax_rate * 100


class Subsession(BaseSubsession):
    # save setting values as an extra column
    def creating_session(self):
        for p in self.get_players():
            p.num_rounds = Constants.num_rounds
            p.treatment = Constants.treatment
            p.tax_rate = Constants.tax_rate


class Group(BaseGroup):

    total_investments = models.FloatField(initial=0)  # define group variable to calculate probabilities

    # determine total investments

    def set_total_investments(self):
        total_investments = sum(p.investment_amount for p in self.get_players())
        # retrieves a list of all individual incomes
        # and sums them up
        self.total_investments = total_investments

    #  calculate probabilities
    def set_probabilities(self):
        self.set_total_investments()
        # probabilities do not add to 1 if all investments are equal (because of floats)
        # this means if all investments or offers are equal
        if len(set(p.investment_amount for p in self.get_players())) == 1:
            for p in self.get_players():
                p.prob = 1 / Constants.players_per_group
        else:
            for p in self.get_players():
                p.prob = p.investment_amount / self.total_investments
        for p in self.get_players():
            p.prob_percent = p.prob * 100

    # determine winner
    def set_winner(self):
        prob = [
            p.prob for p in self.get_players()  # creates list of probabilities
            ]
        prob2 = []  # creates empty list to be normalized in next step
        for i in prob:
            prob2.append(i / sum(prob))  # this normalizes the variable and makes sure that probabilities sum up to 1
        winner = np.random.choice(self.get_players(), p=prob2)
        winner.is_winner = True
        for p in self.get_players():
            p.participant.vars['is_winner'] = p.is_winner

    # determine income:
    def set_incomes(self):  # income is defined in Tokens. What a player obtains at the end in currency are payoffs
        if Constants.treatment:  # if taxation and redistribution are implemented. Only work income is taxed.
            for p in self.get_players():
                if self.round_number > 1:
                    if p.in_round(self.round_number - 1).is_winner:
                        p.income_strings_gross = p.production_strings * Constants.tokensper_string_high
                        p.income_strings_after_tax = p.income_strings_gross * (1 - Constants.tax_rate)
                    else:
                        p.income_strings_gross = p.production_strings * Constants.tokensper_string
                        p.income_strings_after_tax = p.income_strings_gross * (1 - Constants.tax_rate)

                else:   # in the first round all start equally
                    p.income_strings_gross = p.production_strings * Constants.tokensper_string
                    p.income_strings_after_tax = p.income_strings_gross * (1 - Constants.tax_rate)

        else:   # if taxation and redistribution are NOT implemented
            for p in self.get_players():
                if self.round_number > 1:
                    if p.in_round(self.round_number - 1).is_winner:
                        p.income_strings_gross = p.production_strings * Constants.tokensper_string_high
                        p.income_strings_after_tax = p.income_strings_gross
                    else:
                        p.income_strings_gross = p.production_strings * Constants.tokensper_string
                        p.income_strings_after_tax = p.income_strings_gross
                else:   # in the first round all start equally
                    p.income_strings_gross = p.production_strings * Constants.tokensper_string
                    p.income_strings_after_tax = p.income_strings_gross


    # determine redistribution

    total_fiscal = models.FloatField(initial=0)
    transfer = models.FloatField(initial=0)  # the amount per round that each participant receives

    def set_fiscal(self):
        if Constants.treatment:  # if taxation and redistribution are implemented
            # define sum to be redistributed:
            for p in self.get_players():
                p.taxation = p.income_strings_gross * Constants.tax_rate
            total_fiscal = sum(p.taxation for p in self.get_players())

            self.total_fiscal = total_fiscal

            # Redistribute total Budget equally among participants
            for p in self.get_players():
                self.transfer = self.total_fiscal/Constants.players_per_group
                p.available_income = self.transfer + p.income_strings_after_tax
                p.net_income = p.income_strings_after_tax + p.income_in_switch + self.transfer

        else:  # if taxation and redistribution are NOT implemented
            for p in self.get_players():
                p.available_income = p.income_strings_gross
                p.net_income = p.income_strings_gross + p.income_in_switch

    # determine payoffs:
    def set_payoffs(self):
        for p in self.get_players():
            p.earnings = p.net_income - p.investment_amount
            p.payoff = p.earnings * Constants.eurosper_token


class Player(BasePlayer):

    # create a column for each constant
    num_rounds = models.PositiveIntegerField()
    treatment = models.BooleanField()
    tax_rate = models.FloatField()

    # give each player a letter for identification (Important for Feedback)
    def role(self):
        return string.ascii_uppercase[self.id_in_group - 1]

    # Beliefs Variables

    investment_belief_0 = models.FloatField()
    investment_belief_1 = models.FloatField()

    production_belief_0 = models.PositiveIntegerField()
    production_belief_1 = models.PositiveIntegerField()

    # Contest Variables
    is_winner = models.BooleanField(
        initial=False,
        doc="""Indicates whether the player is the winner of the Tullock Contest"""
    )

    prob = models.FloatField(
        doc="Probabilities of getting the Prize in the next round. Tullock"
    )

    prob_percent = models.FloatField(
        doc="Probabilities in percent of getting the prize in next round. Tullock"
    )
    investment_amount = models.FloatField(
        default=0,
        doc="Amount bidden by the player"
    )

    # Real Effort Task variables
    # Number of Tasks Solved
    production_strings = models.FloatField(default=0)
    income_in_switch = models.FloatField(default=0)
    total_production = models.FloatField(default=0)  # the sum in tokens of earnings from string solving (gross) and switch

    # available income after solving RET
    income_strings_gross = models.FloatField(default=0)
    income_strings_after_tax = models.FloatField(default=0)
    income_after_redistribution = models.FloatField(default=0)
    net_income = models.FloatField(default=0)
    available_income = models.FloatField(default=0)  # what players are allowed to invest
    earnings = models.FloatField(default=0)  # what players keep after redistribution *and* investment
    taxation = models.FloatField(default=0)  # amount taxed for given participant

    # Variable is 1 when entering switch
    switch1 = models.PositiveIntegerField(default=0)  # word "switch" cannot be used as a variable in javascript

    switch_time = models.PositiveIntegerField(default=0)

    time_in_switch = models.PositiveIntegerField(default=0)

    additional_time = models.PositiveIntegerField(default=0)

    # correct to allow a variable number of tasks
    # for now, created with:
    # for i in range(10, 46):
    # print('t1{} = models.PositiveIntegerField(default=0)'.format(i))

    # def set_time_fields(self):
    #     for i in range(31):
    #         self.participant.vars['t1{}'.format(i)] = models.PositiveIntegerField(default=0)
    #     print(self.participant.vars)

    # Time Needed to Solve Task i in Round j with tjxi
    t101 = models.PositiveIntegerField(default=0)
    t102 = models.PositiveIntegerField(default=0)
    t103 = models.PositiveIntegerField(default=0)
    t104 = models.PositiveIntegerField(default=0)
    t105 = models.PositiveIntegerField(default=0)
    t106 = models.PositiveIntegerField(default=0)
    t107 = models.PositiveIntegerField(default=0)
    t108 = models.PositiveIntegerField(default=0)
    t109 = models.PositiveIntegerField(default=0)
    t110 = models.PositiveIntegerField(default=0)
    t111 = models.PositiveIntegerField(default=0)
    t112 = models.PositiveIntegerField(default=0)
    t113 = models.PositiveIntegerField(default=0)
    t114 = models.PositiveIntegerField(default=0)
    t115 = models.PositiveIntegerField(default=0)
    t116 = models.PositiveIntegerField(default=0)

templates/tullock_income_ret/BeliefsInvestment.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}
{% load staticfiles %}


{% block title %}
    Your Beliefs Round 2.{{ subsession.round_number }}
{% endblock %}

{% block styles %}
    <link href="{% static "tullock_income_ret/css/Belief.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<hr>

Please answer the following questions:
    <br>
    <br>
<ol type="1"> <!-- This starts a numbered list -->


   <li> How much do you think will player {{ player.get_others_in_group.0.role }} invest in the present round (2.{{ subsession.round_number }})?:
       {% formfield player.investment_belief_0 label="" %} </li>

   <li> How much do you think will player {{ player.get_others_in_group.1.role }} invest in the present round (2.{{ subsession.round_number }})?:
       {% formfield player.investment_belief_1 label="" %} </li>

</ol>


<br>
    {% next_button %}

{% endblock %}

templates/tullock_income_ret/BeliefsProduction.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}
{% load staticfiles %}


{% block title %}
    Your Beliefs Round 2.{{ subsession.round_number }}
{% endblock %}

{% block styles %}
    <link href="{% static "tullock_income_ret/css/Belief.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<hr>

Please answer the following questions:
    <br>
    <br>
<ol type="1"> <!-- This starts a numbered list -->


   <li> How many sequences do you think will player {{ player.get_others_in_group.0.role }} solve in the present round (2.{{ subsession.round_number }})?:
       {% formfield player.production_belief_0 label="" %} </li>

   <li> How many sequences do you think will player {{ player.get_others_in_group.1.role }} solve in the present round (2.{{ subsession.round_number }})?:
       {% formfield player.production_belief_1 label="" %} </li>

</ol>


<br>
    {% next_button %}

{% endblock %}

templates/tullock_income_ret/CompetitionInstructions1.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}
{% load humanize %}

{% block title %}
    Grouping
{% endblock %}

{% block content %}
<hr>
   <div class="card bg-light instructions">
   <div class="card-body">

    <p>
        Until now you have played on your own. Now, you have been randomly allocated into a group of {{ Constants.players_per_group|apnumber }} participants: A, B and C<br>
        You are participant <strong>{{ player.role }}</strong>.
        <br>
    </p>
       <p>
        Your decisions and results will be absolutely anonymous. Your identity will neither be revealed to your co-participants nor to the experimenters
        at any time during or after the experiment.</p>
    <p>
        There will be <strong>{{ Constants.num_rounds|apnumber }} rounds</strong> of {{ Constants.time_in_minutes|apnumber }} minutes.
        You and the other group members will be performing the same type of task as in the rounds before.</p>
    <p>
        <div class="card card-primary border-primary mb-3">
         <div class="card-body">
        <p>
        In the <strong>first round all participants will have the same wage </strong> of 1 Token per correctly solved sequence.
       </p>
    <p>
        In all the <strong>following rounds</strong> exactly <strong>one out of the {{ Constants.players_per_group|apnumber }} group members</strong> will get
        a wage of <strong><em>{{ Constants.tokensper_string_high|apnumber }} tokens</em></strong> per correct sequence.
       The other players will keep their wage of {{ Constants.tokensper_string|apnumber }} token per string. All participants in all rounds will get 1 token per
       {{ Constants.secondsper_token }} seconds spent in "switch".
   </p>
       {% if Constants.treatment %}
       <p>
       Your income from solving sequences will be taxed at at rate of {{ Constants.tax_rate_percent }}%. The taxes collected from all participants in your group
       will be equally distributed among the group after each round.
       </p>
       {% endif %}
        </div>
        </div>
    <p>
    {% if Constants.treatment %}

        To win the higher wage you will have the opportunity to invest your earnings from counting "a"s in the <i>Letter Counting Task</i> (but not those from spending time in "switch")
        plus your share of the redistributed taxes.<br>
        For instance, if you solved 10 sequences with a wage of 1 Token per sequence your income after taxation of 30% is equal to 7 token.
        Assuming that you get 2 Tokens from redistribution, your total available income for investing would be equal to 9 tokens.

    {% else %}
        To win the higher wage you will have the opportunity to invest some of your earnings from counting "a"s in the <i>Letter Counting Task</i>
        (but not those from spending time in "switch").
    {% endif %}
    </p>
    <p>
        Your probability of obtaining the higher wage is equal to your share of all the investments in your group. You can keep the tokens that you do not invest,
        but your investment will not be refunded if you do not win the prize. You cannot use your earnings from previous rounds.
        The more you invest, the higher are your chances!
    </p>
    <p>
        On the next screen, you will see an illustrative example of how the prize is awarded.</p>
   </div>
   </div>

    {% next_button %}

{% endblock %}

templates/tullock_income_ret/CompetitionInstructions2Example.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}



{% block styles %}

<!-- CSS Styling for Table

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;border-color:#999;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#999;color:#444;background-color:#F7FDFA;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#999;color:#fff;background-color:#26ADE4;}
.tg .tg-s6z2{text-align:center}
@media screen and (max-width: 767px) {.tg {width: auto !important;}.tg col {width: auto !important;}.tg-wrap {overflow-x: auto;-webkit-overflow-scrolling: touch;}}</style>
-->
<!-- CSS Styling for Box around Text

<style>
.border
{
border:1px;
border-style:solid;
border-color:#287EC7;
padding: 1em;
}
</style> -->
{% endblock %}


{% block title %}
    Investment Example
{% endblock %}

{% block content %}
<hr>
<div class="card card-primary">
  <!-- Default panel contents -->
<div class="card-header text-white bg-primary mb-3">Group Investments</div>
  <div class="card-body">
    Here you can see an illustrative example of individual and group investments:
    <br>
      <br>


<!-- Begin Table -->
<table class="table">
  <thead>
  <tr>
    <th class="tg-s6z2">Player</th>
    <th class="tg-s6z2">Investment</th>
    <th class="tg-s6z2">Share of total<br>Group Investment</th>
    <th class="tg-s6z2">Probability of receiving<br><em>double payoff</em></th>
  </thead>
  </tr>
  <tr>
    <td class="tg-s6z2">A</td>
    <td class="tg-s6z2">16</td>
    <td class="tg-s6z2">40.0 %</td>
    <td class="tg-s6z2">40.0 %</td>
  </tr>
  <tr>
    <td class="tg-s6z2">B</td>
    <td class="tg-s6z2">14</td>
    <td class="tg-s6z2">35.0 %</td>
    <td class="tg-s6z2">35.0 %</td>
  </tr>
  <tr>
    <td class="tg-s6z2">C</td>
    <td class="tg-s6z2">10</td>
    <td class="tg-s6z2">25.0 %</td>
    <td class="tg-s6z2">25.0 %</td>
  </tr>
  <tfoot>
  <tr>
    <td class="tg-s6z2">Total</td>
    <td class="tg-s6z2">40</td>
    <td class="tg-s6z2">100 %</td>
    <td class="tg-s6z2"></td>
  </tr>
  </tfoot>
</table>
  </div>
</div>

<!-- End Table -->
<br>
    <div class="card bg-light instructions">
    <div class="card-body">

   <p>
	In this scenario, participant A invested 16 tokens which corresponds to 40 % of the sum of all investments by the group members.<br>
	Therefore, participant A will get the <em>higher wage</em> in the next round with a probability of 40 %.</p>
    <hr>

    <p>
        Making an investment can potentially increase your earnings in the following period but will reduce your earnings for the current period.
    </p>
        <div class="card card-primary border-primary mb-3">
            <div class="card-header">Your Earnings in the Previous Rounds</div>
         <div class="card-body">
             In the first round, <strong>with the wage of {{ Constants.tokensper_string }} Token per sequence</strong>, your earned:
             <div class="badge badge-dark">
                 {{ income_1 }} Tokens
             </div>
        <br>
             In the second round, <strong>with the wage of {{ Constants.tokensper_string_high }} Tokens per sequence</strong>, you earned
             <div class="badge badge-dark">
             {{ income_2 }} Tokens
             </div>
         </div>
        </div>
    </div>
    </div>

  {% next_button %}



{% endblock %}

templates/tullock_income_ret/Investment.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Investment Round 2.{{ subsession.round_number }}
{% endblock %}

{% block styles %}
<link href="{% static "tullock_income_ret/jquery-ui/jquery-ui.min.css" %}" rel="stylesheet">
<style type="text/css">
    .bid-slider {
        margin: 1.5em auto;
        width: 70%;
    }

    .bid {
        text-align: center;
    }

    .payoff {
        margin: 1.5em 0;
    }
</style>
{% endblock %}


{% block content %}
<hr>

    <div class="card">
        <div class="card-header text-white bg-primary mb-3"> Submit your investment:</div>
    <div class="card-body">

    <p>
        Your disposable income is <strong>{{ player.available_income|floatformat:2 }} Token</strong>.
    </p>

    <div class="form-group required">
        <label class="control-label" for="id_investment_amount">Please submit your investment (from 0 to {{ player.available_income|floatformat:0 }}):</label>
        <div class="controls">
            <input type="hidden" name="investment_amount" id="id_investment_amount" value="0">
            <div class="bid-slider"></div>
            <div class="bid">Your investment: <strong><span class="bid-value"></span> </strong>Tokens.
                <p>
                You keep <strong><span class="payoff-value"></span></strong> Tokens plus your earnings from "switch".</div>
                </p>
            <div class="payoff">
                <p>
                    If you win the contest, you will earn a wage of <strong>{{Constants.tokensper_string_high}} Tokens per sequence.</strong>
                If you lose it, a wage of <strong>{{Constants.tokensper_string}}</strong> Token. The money you invest will not be refunded.
                </p>
            </div>
        </div>
         </div>
    </div>
    </div>

    <br>
    {% next_button %}


    {{ form.investment_amount.errors }}

{% endblock %}


{% block scripts %}
<script src="{% static "tullock_contest/jquery-ui/jquery-ui.min.js" %}"></script>
<script>
jQuery(document).ready(function ($) {
    var INCOME = {{ income }};

    var input = $('#id_investment_amount');

    $('.bid-slider').slider({
        min: 0,
        max: INCOME,
        step: 0.2,
        // make values below 0 and over 1 snap back
        slide: function (event, ui) {
            input.val(ui.value);
            updateBidValue();
        }
    });

    function updateBidValue() {
        $('.bid-value').text(input.val());
        $('.payoff-value').text(calculatePayoff());
    }

    function calculatePayoff() {
        var value = parseFloat(input.val()).toFixed(2); //ParseFloat reduces float to two decimals
        var payoff = parseFloat(INCOME - value).toFixed(2); //ParseFloat reduces float to two decimals
        return payoff;
    }

    updateBidValue();
});
</script>
{% endblock %}

templates/tullock_income_ret/RET.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}


{% block styles %}
    <link href="{% static "tullock_income_ret/css/Round.css" %}" rel="stylesheet">
{% endblock %}

{% block title %}
    Letter Counting Task Round 2.{{ subsession.round_number }}
{% endblock %}

{% block content %}

<div class="jumbotron">

<span class="badge badge-primary"  data-toggle="tooltip" data-placement="top" title="Time spent in current sequence">
<span id="min">00</span>:<span id="sec">00</span>
</span>

    <br>
    <span class="badge badge-success" id="number_strings"  data-toggle="tooltip" data-placement="bottom" title="Number of sequences solved" >00</span>

<div id="string">
</div>

<br>

<input type="number" id="player_guess" size="4" autofocus>
</input> &nbsp;

<br>

<input type="hidden" name="production_strings" id="id_production_strings"/>

<p align="right">


<!-- "Switch" Confirmation -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  SWITCH
</button>

<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirm</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to go into "switch" mode?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" id="Switch_button" data-dismiss="modal">Switch</button>
      </div>
    </div>
  </div>
</div>
</p>


</div>




<!-- "Switch" Mode -->

<div id="Switch_mode" class="Switch_mode">
    <div class="card">
    <div class="card-header text-white bg-primary mb-3">
        <h5>You are now in the "Switch" mode</h5>
        </div>
        <div class="card-body">
        <p>
            You solved <span class="badge badge-success"> <span name="sequences_solved" id="sequences_solved"></span> </span> sequences.
        </p>

        Your earnings from "Switch" mode are:
        <br>
        <h3>
        <span class="badge badge-primary"><span id="token_counter">00</span> Tokens
        </span>
        </h3>
        </div>
    </div>
    </div>
</div>

    <br>

<input type="hidden" name="switch1" id="id_switch1"/>

{{ form.errors }}

    {% include Constants.instructions_summarized %}

{% endblock %}

{% block scripts %}
        <!-- this needs to be in a separate file. -->
<script>


//this initiates the tooltip mouseover to explain the counters
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
//

var string_list = {{ session.vars.string_list|json }};
var a_count = {{ session.vars.a_count|json }};
var length_1 = a_count.length;

var me = me || {};
me.index = null;
me.guess = null;
me.timer = null;
me.pad = null;
me.settime = null;
me.resettime = null;
me.check = null;
me.makeguess = null;

// This function adds an additional "0" left to single digit numbers for formatting reasons, not for functionality
// is called repeatedly from within settime and resettime functions
me.pad = function(val) {
    return val > 9 ? val : "0" + val;
};

// This function first sets the time to zero and then increments the counter every 1000ms by 1. Minutes (sec modulo 60) and seconds separately
// only called once at window.onload
me.settime = function() {
    me.sec = 0;
    me.timer = setInterval(function () {
        document.getElementById("sec").innerHTML = me.pad(++me.sec % 60);
        document.getElementById("min").innerHTML = me.pad(parseInt(me.sec / 60, 10));
        }, 1000)
};

// This function stops the active timer and sets the display to 00:00. Subsequently, the timer is restarted.
// is called by function makeguess on keydown event xxx -> potentially contributing to our problem, removed for testing
me.resettime = function(){
    clearInterval(me.timer);
    document.getElementById("sec").innerHTML = "00";
    document.getElementById("min").innerHTML = "00";

    me.sec = 0;
    me.timer = setInterval(function () {
        document.getElementById("sec").innerHTML = me.pad(++me.sec % 60);
        document.getElementById("min").innerHTML = me.pad(parseInt(me.sec / 60, 10));
        }, 1000)
};

// This function checks whether the correct number of "a"s was provided
// resets the input text field to empty
me.check = function(x) {
    document.getElementById("player_guess").value = "";

    var el = document.createElement("input")
    el.type = "hidden";
    if (me.index+1 < 10){
        el.name = "t10" + (me.index+1);
    } else{
        el.name = "t1" + (me.index+1);
    }
    el.value = me.sec;
    el.id = el.name;

    var answers = document.getElementById("id_production_strings");
    answers.appendChild(el);

    if (x === a_count[me.index]) {
        me.makeguess(me.index+1);
        me.resettime();
    } else {
        me.makeguess(me.index);
    }
};

// This function loads and displays the next string
// it also counts the number of strings correctly solved
me.makeguess = function(x) {
    if (x >= length_1) {
        alert("Error");
    } else {
        me.index = x;

        var string = document.getElementById("string");
        string.innerHTML = string_list[x];

        number_strings = x;
        document.getElementById("number_strings").innerHTML = number_strings;

        document.getElementById("id_production_strings").setAttribute("value",me.index);
    }
};


// This function is called by the keydown event handler
// it resets the time and triggers the checking function
function keyDownTextField(e) {
  var keyCode = e.keyCode;
  if(keyCode==13) {
    event.preventDefault();
    var wert = document.getElementById("player_guess").value;
    me.guess = parseInt(wert);
    me.check(me.guess);
    }
}

// This function is called by the keyup event handler and only blocks the enter button
function keyUpTextField(e) {
  var keyCode = e.keyCode;
  if(keyCode==13) {
    event.preventDefault();
  }
}

// This function is called by the keypress event handler and only blocks the enter button
function keyPressTextField(e) {
  var keyCode = e.keyCode;
  if(keyCode==13) {
    event.preventDefault();
  }
}

// The following sends the participant to "switch" mode

document.getElementById("Switch_button").addEventListener("click", function() {
    event.preventDefault();
    var el = document.createElement("input");
    el.type = "hidden";
    el.name = "additionaltime1";
    el.value = me.sec;
    el.id = el.name;
    var answers = document.getElementById("id_production_strings");
    answers.appendChild(el);
    var pattern = document.getElementsByClassName("jumbotron")[0];
        pattern.classList.add("d-none");
    var switchmode = document.getElementsByClassName("Switch_mode");
        switchmode[0].classList.remove("d-none");
    var switch1 = 1;
        document.getElementById("id_switch1").setAttribute("value",switch1);

    var tokens = 0;
    var counter = document.getElementById('token_counter');

    // This functions counts the earnings in "switch" dynamically and shows the total of strings solved
    function incrementSeconds() {
    tokens += 0.1;
    counter.innerText = Math.round( tokens * 10 ) / 10;
    }

    var cancel = setInterval(incrementSeconds, 1000);

    var sequences_solved = number_strings;
    var sequences = document.getElementById("sequences_solved");
    sequences.innerText = sequences_solved;

});

// displays the first string and starts the counter
// Importantly, the event handlers are only called here once!!!
window.onload = function(){
    me.makeguess(0);
    me.settime();
    var switchmode = document.getElementsByClassName("Switch_mode");
    switchmode[0].classList.add("d-none");
    document.addEventListener("keydown", keyDownTextField, false);
    document.addEventListener("keyup", keyUpTextField, false);
    document.addEventListener("keypress", keyPressTextField, false);
};
    </script>
{% endblock %}

templates/tullock_income_ret/StartSubmit.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Start Confirmation
{% endblock %}

{% block content %}
<hr>

    <div class="jumbotron">
        In the next screen you will have the opportunity to earn money as explained in the screens before.
    </p>
    <h1>Are you ready to start?</h1>
        <p>
            Pressing the <span class="badge badge-danger">Start</span> button will start the letter counting task
        </p>
        <br>
        <br>
        <br>
    <button class="btn btn-danger btn-block">Start</button>
    </div>

{% endblock %}